<?php
/**
 * CompanyProductCreateParametersTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Coupons Api
 *
 * TrustAndUse coupons api in the swagger-2.0 specification
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sp@7indigo.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CompanyProductCreateParametersTest Class Doc Comment
 *
 * @category    Class */
// * @description CompanyProductCreateParameters
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CompanyProductCreateParametersTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CompanyProductCreateParameters"
     */
    public function testCompanyProductCreateParameters()
    {

    }

    /**
     * Test attribute "productype"
     */
    public function testPropertyProductype()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "imagesUris"
     */
    public function testPropertyImagesUris()
    {

    }

    /**
     * Test attribute "brandID"
     */
    public function testPropertyBrandID()
    {

    }

    /**
     * Test attribute "userID"
     */
    public function testPropertyUserID()
    {

    }

    /**
     * Test attribute "merchantsids"
     */
    public function testPropertyMerchantsids()
    {

    }

}
