<?php
/**
 * CompanyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Coupons Api
 *
 * TrustAndUse coupons api in the swagger-2.0 specification
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sp@7indigo.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CompanyTest Class Doc Comment
 *
 * @category    Class */
// * @description Company
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CompanyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Company"
     */
    public function testCompany()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "created_by"
     */
    public function testPropertyCreatedBy()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "in_charge_person_name"
     */
    public function testPropertyInChargePersonName()
    {

    }

    /**
     * Test attribute "main_address"
     */
    public function testPropertyMainAddress()
    {

    }

    /**
     * Test attribute "main_image_url"
     */
    public function testPropertyMainImageUrl()
    {

    }

    /**
     * Test attribute "logo_url"
     */
    public function testPropertyLogoUrl()
    {

    }

    /**
     * Test attribute "contact_phone"
     */
    public function testPropertyContactPhone()
    {

    }

    /**
     * Test attribute "company_type"
     */
    public function testPropertyCompanyType()
    {

    }

    /**
     * Test attribute "points_of_interest"
     */
    public function testPropertyPointsOfInterest()
    {

    }

    /**
     * Test attribute "brands"
     */
    public function testPropertyBrands()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "facebook_page_url"
     */
    public function testPropertyFacebookPageUrl()
    {

    }

}
