<?php
/**
 * CompanyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Coupons Api
 *
 * TrustAndUse coupons api in the swagger-2.0 specification
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sp@7indigo.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CompanyTest Class Doc Comment
 *
 * @category    Class */
// * @description Company
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CompanyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Company"
     */
    public function testCompany()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "createdBy"
     */
    public function testPropertyCreatedBy()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "inChargePersonName"
     */
    public function testPropertyInChargePersonName()
    {

    }

    /**
     * Test attribute "mainAddress"
     */
    public function testPropertyMainAddress()
    {

    }

    /**
     * Test attribute "mainImageURL"
     */
    public function testPropertyMainImageURL()
    {

    }

    /**
     * Test attribute "logoURL"
     */
    public function testPropertyLogoURL()
    {

    }

    /**
     * Test attribute "contactPhone"
     */
    public function testPropertyContactPhone()
    {

    }

    /**
     * Test attribute "companyType"
     */
    public function testPropertyCompanyType()
    {

    }

    /**
     * Test attribute "pointsOfInterest"
     */
    public function testPropertyPointsOfInterest()
    {

    }

    /**
     * Test attribute "brands"
     */
    public function testPropertyBrands()
    {

    }

    /**
     * Test attribute "products"
     */
    public function testPropertyProducts()
    {

    }

    /**
     * Test attribute "coupons"
     */
    public function testPropertyCoupons()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "userDefined"
     */
    public function testPropertyUserDefined()
    {

    }

}
