<?php
/**
 * CreateCompanyParametersTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Coupons Api
 *
 * TrustAndUse coupons api in the swagger-2.0 specification
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sp@7indigo.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CreateCompanyParametersTest Class Doc Comment
 *
 * @category    Class */
// * @description CreateCompanyParameters
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateCompanyParametersTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CreateCompanyParameters"
     */
    public function testCreateCompanyParameters()
    {

    }

    /**
     * Test attribute "userID"
     */
    public function testPropertyUserID()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "inChargePersonName"
     */
    public function testPropertyInChargePersonName()
    {

    }

    /**
     * Test attribute "mainAddress"
     */
    public function testPropertyMainAddress()
    {

    }

    /**
     * Test attribute "mainImageURL"
     */
    public function testPropertyMainImageURL()
    {

    }

    /**
     * Test attribute "logoURL"
     */
    public function testPropertyLogoURL()
    {

    }

    /**
     * Test attribute "contactPhone"
     */
    public function testPropertyContactPhone()
    {

    }

    /**
     * Test attribute "companyType"
     */
    public function testPropertyCompanyType()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "userDefinedObject"
     */
    public function testPropertyUserDefinedObject()
    {

    }

}
