<?php
/**
 * UserTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Coupons Api
 *
 * TrustAndUse coupons api in the swagger-2.0 specification
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sp@7indigo.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * UserTest Class Doc Comment
 *
 * @category    Class */
// * @description User
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UserTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "User"
     */
    public function testUser()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {

    }

    /**
     * Test attribute "password"
     */
    public function testPropertyPassword()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "lastName"
     */
    public function testPropertyLastName()
    {

    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {

    }

    /**
     * Test attribute "dateOfBirth"
     */
    public function testPropertyDateOfBirth()
    {

    }

    /**
     * Test attribute "uniqueKey"
     */
    public function testPropertyUniqueKey()
    {

    }

    /**
     * Test attribute "mobile"
     */
    public function testPropertyMobile()
    {

    }

    /**
     * Test attribute "pin"
     */
    public function testPropertyPin()
    {

    }

    /**
     * Test attribute "facebookID"
     */
    public function testPropertyFacebookID()
    {

    }

    /**
     * Test attribute "facebookImageURL"
     */
    public function testPropertyFacebookImageURL()
    {

    }

    /**
     * Test attribute "googleID"
     */
    public function testPropertyGoogleID()
    {

    }

    /**
     * Test attribute "googleImgURL"
     */
    public function testPropertyGoogleImgURL()
    {

    }

}
