<?php
/**
 * BrandApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Coupons Api
 *
 * TrustAndUse coupons api in the swagger-2.0 specification
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sp@7indigo.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * BrandApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BrandApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for addUserBrand
     *
     * .
     *
     */
    public function testAddUserBrand()
    {

    }

    /**
     * Test case for allBrands
     *
     * .
     *
     */
    public function testAllBrands()
    {

    }

    /**
     * Test case for createBrand
     *
     * .
     *
     */
    public function testCreateBrand()
    {

    }

    /**
     * Test case for createCouponBrand
     *
     * .
     *
     */
    public function testCreateCouponBrand()
    {

    }

    /**
     * Test case for createProductBrand
     *
     * .
     *
     */
    public function testCreateProductBrand()
    {

    }

    /**
     * Test case for getBrandDetails
     *
     * .
     *
     */
    public function testGetBrandDetails()
    {

    }

    /**
     * Test case for getBrandProducts
     *
     * .
     *
     */
    public function testGetBrandProducts()
    {

    }

    /**
     * Test case for removeUserBrandPrivileges
     *
     * .
     *
     */
    public function testRemoveUserBrandPrivileges()
    {

    }

    /**
     * Test case for updateBrand
     *
     * .
     *
     */
    public function testUpdateBrand()
    {

    }

}
