<?php
/**
 * CompanyApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Coupons Api
 *
 * TrustAndUse coupons api in the swagger-2.0 specification
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sp@7indigo.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * CompanyApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CompanyApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for addUserCompanyRoles
     *
     * .
     *
     */
    public function testAddUserCompanyRoles()
    {

    }

    /**
     * Test case for companyDelete
     *
     * .
     *
     */
    public function testCompanyDelete()
    {

    }

    /**
     * Test case for companyGetDetails
     *
     * .
     *
     */
    public function testCompanyGetDetails()
    {

    }

    /**
     * Test case for createBrandForCompany
     *
     * .
     *
     */
    public function testCreateBrandForCompany()
    {

    }

    /**
     * Test case for createCompany
     *
     * .
     *
     */
    public function testCreateCompany()
    {

    }

    /**
     * Test case for createCouponForCompany
     *
     * .
     *
     */
    public function testCreateCouponForCompany()
    {

    }

    /**
     * Test case for createProductCompany
     *
     * .
     *
     */
    public function testCreateProductCompany()
    {

    }

    /**
     * Test case for createStoreForCompany
     *
     * .
     *
     */
    public function testCreateStoreForCompany()
    {

    }

    /**
     * Test case for removeAdminUserCompany
     *
     * .
     *
     */
    public function testRemoveAdminUserCompany()
    {

    }

    /**
     * Test case for updateCompany
     *
     * .
     *
     */
    public function testUpdateCompany()
    {

    }

}
