<?php
/**
 * StoreApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Coupons Api
 *
 * TrustAndUse coupons api in the swagger-2.0 specification
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sp@7indigo.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * StoreApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class StoreApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for addUserStore
     *
     * .
     *
     */
    public function testAddUserStore()
    {

    }

    /**
     * Test case for allStores
     *
     * .
     *
     */
    public function testAllStores()
    {

    }

    /**
     * Test case for createCouponStore
     *
     * .
     *
     */
    public function testCreateCouponStore()
    {

    }

    /**
     * Test case for createProductStore
     *
     * .
     *
     */
    public function testCreateProductStore()
    {

    }

    /**
     * Test case for createStore
     *
     * .
     *
     */
    public function testCreateStore()
    {

    }

    /**
     * Test case for getStoreDetails
     *
     * .
     *
     */
    public function testGetStoreDetails()
    {

    }

    /**
     * Test case for removeUserStore
     *
     * .
     *
     */
    public function testRemoveUserStore()
    {

    }

    /**
     * Test case for storeDelete
     *
     * .
     *
     */
    public function testStoreDelete()
    {

    }

    /**
     * Test case for updateStore
     *
     * .
     *
     */
    public function testUpdateStore()
    {

    }

}
