<?php
/**
 * StoreApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Coupons Api
 *
 * TrustAndUse coupons api in the swagger-2.0 specification
 *
 * OpenAPI spec version: 1.0.0
 * Contact: sp@7indigo.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * StoreApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class StoreApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for addUserStore
     *
     * .
     *
     */
    public function testAddUserStore()
    {

    }

    /**
     * Test case for allStores
     *
     * .
     *
     */
    public function testAllStores()
    {

    }

    /**
     * Test case for createCouponStore
     *
     * .
     *
     */
    public function testCreateCouponStore()
    {

    }

    /**
     * Test case for createProductStore
     *
     * .
     *
     */
    public function testCreateProductStore()
    {

    }

    /**
     * Test case for createStore
     *
     * .
     *
     */
    public function testCreateStore()
    {

    }

    /**
     * Test case for getStoreDetails
     *
     * .
     *
     */
    public function testGetStoreDetails()
    {

    }

    /**
     * Test case for removeUserStore
     *
     * .
     *
     */
    public function testRemoveUserStore()
    {

    }

    /**
     * Test case for storeDelete
     *
     * .
     *
     */
    public function testStoreDelete()
    {

    }

    /**
     * Test case for updateStore
     *
     * .
     *
     */
    public function testUpdateStore()
    {

    }

}
